### ISSUE TITLE
Citer un commentaire de visiteur

### ISSUE THREAD

**Issue by jemattarde** [franck-paul/commentsWikibar#14]
Bonjour,
C'est une demande d'amélioration. C'est subjectif mais je trouve l'usage des boutons associés aux balises quote ou blockquote assez peu pratiques dans le contexte du fil des commentaires. Ce serait super si il était possible de citer une partie d'un commentaire d'un visiteur et de n'avoir que ce bouton comme choix dans la wiki barre. Quelque chose comme [cite=jojo]blablaba[/cite] à l'instar du forum dotclear et ainsi voir apparaître le nom du visiteur en préambule de la citation

**Comment by franck-paul** [comment]
Bonjour,

Ça dépasse le périmètre de ce plugin qui se contente de fournir des boutons pour insérer plus facilement des balises Wiki ou Markdown. Ça évite d'avoir à connaître par cœur la syntaxe à utiliser, rien de plus.

Par contre il me semble qu'il existe un plugin pour gérer les réponses à un autre commentaire mais je ne connais pas son statut de maintenance (https://plugins.dotaddict.org/dc2/details/atReply).

**Comment by jemattarde** [comment]
Merci, je comprends.

Une question complémentaire : combiner la syntaxe Bbcode et markdown dans les commentaires, c'est jouable ? Difficile ?

Hormis ce plugin : 
http://www.k-netweb.net/blog/?post/2007/02/03/Plugin-DotClear-2-%3A-Custom-Code

Avez-vous connaissance de choses plus récentes en Bbcode sur dc ?

Gilles

**Comment by franck-paul** [comment]
Nope rien à ma connaissance.

Quant à mixer Markdown et BBCode je pense personnellement que ce n'est pas souhaitable, surtout qu'on peut déjà mixer Markdown et HTML, voire même avec la syntaxe wiki insérer du Markdown avec la macro `///md`.
