### ISSUE TITLE
Version minimum erronée

### ISSUE THREAD

**Issue by Gvx-** [franck-paul/commentsWikibar#8]
La version minimum du core 2.13 ne convient pas.

Tu utilises dcUtils::jsJson apparu dans le core 2.15 il me semble.

**Comment by franck-paul** [comment]
> La version minimum du core 2.13 ne convient pas.
> 
> Tu utilises dcUtils::jsJson apparu dans le core 2.15 il me semble.

Ah oui tu as raison, bien vu ! Merci Gvx
