### ISSUE TITLE
CSS du textarea 

### ISSUE THREAD

**Issue by franck-tomek** [franck-paul/commentsWikibar#9]
L'activation du plugin modifie la disposition du textarea -> suppression de la bordure, décalage de 5px vers la droite avec ces éléments de CSS intégrés au plugin : 
`.jstEditor {padding-left: 5px;} `
`.jstEditor textarea {border: 0;}`

Ne voyant pas trop ce que ça amène, et étant pénible à corriger (obligation de passer par des !important), je me demandais si on ne pourrait pas supprimer ces règles CSS ennuyeuses.

**Comment by franck-paul** [comment]
Je vais regarder ça
